# Generated by Django 4.2 on 2023-07-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('account_number', models.CharField(max_length=100)),
                ('balance', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('address', models.CharField(default='Sin Direccion', max_length=250)),
                ('phone', models.CharField(default='Ninguno', max_length=25)),
                ('customer_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50)),
                ('wallet_number', models.CharField(max_length=50)),
                ('beneficiary_id', models.CharField(max_length=100, null=True)),
                ('balance', models.CharField(default=0, max_length=100)),
            ],
        ),
    ]
