# Generated by Django 3.1.2 on 2020-10-26 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='address',
            field=models.CharField(default='Sin Direccion', max_length=250),
        ),
        migrations.AddField(
            model_name='customers',
            name='phone',
            field=models.CharField(default='Ninguno', max_length=25),
        ),
    ]
