# Generated by Django 4.2 on 2023-04-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_order_is_delivered'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('account_number', models.CharField(max_length=100)),
                ('balance', models.CharField(max_length=100)),
            ],
        ),
    ]
