# Generated by Django 4.2 on 2023-07-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_wallet_account_number_alter_wallet_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='beneficiary_id',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
