# Generated by Django 4.2 on 2023-07-03 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_wallet_beneficiary_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='beneficiary_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
